name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: ["Debug", "Release"]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}
    
    - uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.build-type}}
        path: ${{github.workspace}}/build/${{matrix.build-type}}
